//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEyeEntities2 : DbContext
    {
        public DBEyeEntities2()
            : base("name=DBEyeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t店家> t店家 { get; set; }
        public virtual DbSet<t訂單> t訂單 { get; set; }
        public virtual DbSet<t訂單明細> t訂單明細 { get; set; }
        public virtual DbSet<t產品> t產品 { get; set; }
        public virtual DbSet<t換貨> t換貨 { get; set; }
        public virtual DbSet<t換貨明細> t換貨明細 { get; set; }
        public virtual DbSet<t優惠活動> t優惠活動 { get; set; }
    }
}
