//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t售後服務申請
    {
        public int f售後服務申請Id { get; set; }
        public string f產品名稱 { get; set; }
        public string f產品顏色 { get; set; }
        public string f近視老花度數 { get; set; }
        public string f閃光度數 { get; set; }
        public string f閃光角度 { get; set; }
        public Nullable<decimal> f換貨單價 { get; set; }
        public string f換貨原因 { get; set; }
        public string f換貨備註 { get; set; }
        public Nullable<int> f數量 { get; set; }
        public string f售後服務申請對外Id { get; set; }
    }
}
