//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t店家
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t店家()
        {
            this.t訂單 = new HashSet<t訂單>();
            this.t產品 = new HashSet<t產品>();
            this.t換貨 = new HashSet<t換貨>();
        }
    
        public int f店家ID { get; set; }
        public string f店家名稱 { get; set; }
        public string f店家負責人 { get; set; }
        public string f店家連絡電話 { get; set; }
        public string f註冊日期 { get; set; }
        public string f地址 { get; set; }
        public string f電子信箱 { get; set; }
        public string f密碼 { get; set; }
        public string f身分別 { get; set; }
        public string f往來狀態 { get; set; }
        public string f銀行帳號 { get; set; }
        public string f藥商許可證照片路徑 { get; set; }
        public string f營業登記許可照片路徑 { get; set; }
        public string f備註 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂單> t訂單 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t產品> t產品 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t換貨> t換貨 { get; set; }
    }
}
