//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t換貨明細
    {
        public int f換貨明細ID { get; set; }
        public Nullable<int> f換貨單號ID { get; set; }
        public Nullable<int> f產品ID { get; set; }
        public Nullable<int> f換貨數量 { get; set; }
        public Nullable<decimal> f換貨單價 { get; set; }
        public Nullable<int> f要換的產品ID { get; set; }
        public Nullable<int> f要換的數量 { get; set; }
        public Nullable<decimal> f要換的產品單價 { get; set; }
        public string f售後服務申請對外Id { get; set; }
    
        public virtual t換貨 t換貨 { get; set; }
    }
}
