//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t換貨
    {
        public int f換貨單號ID { get; set; }
        public Nullable<int> f店家ID { get; set; }
        public string f申請日期 { get; set; }
        public string f連絡電話 { get; set; }
        public string f換貨申請人 { get; set; }
        public string f換貨原因 { get; set; }
        public string f換貨申請狀態 { get; set; }
        public string f對外訂單單號 { get; set; }
    }
}
