//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace contact.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class t產品
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t產品()
        {
            this.t訂單明細 = new HashSet<t訂單明細>();
            this.t換貨明細 = new HashSet<t換貨明細>();
        }
    
        public int f產品ID { get; set; }
        public string f製造批號 { get; set; }
        public Nullable<int> f店家ID { get; set; }
        public string f店家名稱 { get; set; }
        public string f品牌名稱 { get; set; }
        public string f產品名稱 { get; set; }
        public string f近視老花度數 { get; set; }
        public string f閃光度數 { get; set; }
        public string f閃光角度 { get; set; }
        public Nullable<int> f庫存數量 { get; set; }
        public string f數量單位 { get; set; }
        public Nullable<decimal> f成本價 { get; set; }
        public Nullable<decimal> f售價 { get; set; }
        public string f製造期限 { get; set; }
        public string f有限期限 { get; set; }
        public string f產品圖片路徑 { get; set; }
        public string f產品描述 { get; set; }
        public string f對外產品識別ID { get; set; }
        public string f產品顏色 { get; set; }
    
        public virtual t店家 t店家 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂單明細> t訂單明細 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t換貨明細> t換貨明細 { get; set; }
        public HttpPostedFileBase photo { get; set; }

    }
}
